"""empty message

Revision ID: 3c27419ae40b
Revises: 8d456008e131
Create Date: 2026-02-15 07:09:59.947000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c27419ae40b'
down_revision = '8d456008e131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('original_role')

    # ### end Alembic commands ###
