"""empty message

Revision ID: 5eeeb821661a
Revises: 94f9e84e9de9
Create Date: 2026-02-16 05:13:08.420483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eeeb821661a'
down_revision = '94f9e84e9de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptiondetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=30), nullable=False))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptiondetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
