"""empty message

Revision ID: 8d456008e131
Revises: 
Create Date: 2026-02-15 06:00:44.660883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d456008e131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('centerID', sa.Integer(), nullable=False),
    sa.Column('centerName', sa.String(length=40), nullable=False),
    sa.Column('centerType', sa.String(length=30), nullable=False),
    sa.Column('centerLocation', sa.String(length=20), nullable=False),
    sa.Column('centerManager', sa.String(length=40), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('centerID')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userID', sa.String(length=36), nullable=True),
    sa.Column('centerID', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('phonenumber', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('password_set', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('last_failed_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['centerID'], ['centers.centerID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phonenumber'),
    sa.UniqueConstraint('userID'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auditlogs',
    sa.Column('logID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=300), nullable=True),
    sa.Column('entity', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('logID')
    )
    op.create_table('patients',
    sa.Column('patientID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.String(length=36), nullable=False),
    sa.Column('hospitalID', sa.Integer(), nullable=True),
    sa.Column('pharmacyID', sa.Integer(), nullable=True),
    sa.Column('omangnumber', sa.String(length=9), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('Male', 'Female', name='sextype'), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospitalID'], ['centers.centerID'], ),
    sa.ForeignKeyConstraint(['pharmacyID'], ['centers.centerID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('patientID')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_omangnumber'), ['omangnumber'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_userID'), ['userID'], unique=True)

    op.create_table('appointments',
    sa.Column('appointmentID', sa.Integer(), nullable=False),
    sa.Column('patientID', sa.Integer(), nullable=False),
    sa.Column('doctorID', sa.String(length=36), nullable=False),
    sa.Column('centerID', sa.Integer(), nullable=False),
    sa.Column('appointmentDateTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointmentNotes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Scheduled', 'Completed', 'Cancelled', 'No Show', name='appointmentstatus'), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['centerID'], ['centers.centerID'], ),
    sa.ForeignKeyConstraint(['doctorID'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientID'], ['patients.patientID'], ),
    sa.PrimaryKeyConstraint('appointmentID')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_appointmentDateTime'), ['appointmentDateTime'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_centerID'), ['centerID'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_doctorID'), ['doctorID'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patientID'), ['patientID'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    op.create_table('diagnosis',
    sa.Column('diagnosisID', sa.Integer(), nullable=False),
    sa.Column('patientID', sa.Integer(), nullable=False),
    sa.Column('doctorID', sa.String(length=36), nullable=False),
    sa.Column('diagnosisSummary', sa.String(length=250), nullable=False),
    sa.Column('diagnosisDetails', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('Mild', 'Moderate', 'Severe', 'Critical', name='diagnosisseverity'), nullable=False),
    sa.Column('diagnosisDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctorID'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientID'], ['patients.patientID'], ),
    sa.PrimaryKeyConstraint('diagnosisID')
    )
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_diagnosisDate'), ['diagnosisDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_doctorID'), ['doctorID'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_patientID'), ['patientID'], unique=False)

    op.create_table('prescriptions',
    sa.Column('prescriptionID', sa.Integer(), nullable=False),
    sa.Column('patientID', sa.Integer(), nullable=False),
    sa.Column('doctorID', sa.String(length=36), nullable=False),
    sa.Column('diagnosisID', sa.Integer(), nullable=False),
    sa.Column('appointmentID', sa.Integer(), nullable=False),
    sa.Column('dateIssued', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Pending', 'Partially Filled', 'Dispensed', name='prescriptionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['appointmentID'], ['appointments.appointmentID'], ),
    sa.ForeignKeyConstraint(['diagnosisID'], ['diagnosis.diagnosisID'], ),
    sa.ForeignKeyConstraint(['doctorID'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patientID'], ['patients.patientID'], ),
    sa.PrimaryKeyConstraint('prescriptionID')
    )
    op.create_table('prescriptiondetails',
    sa.Column('prescriptionDetailID', sa.Integer(), nullable=False),
    sa.Column('prescriptionID', sa.Integer(), nullable=False),
    sa.Column('medicineName', sa.String(length=50), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.String(length=250), nullable=True),
    sa.Column('isDispensed', sa.Boolean(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispensed_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescriptionID'], ['prescriptions.prescriptionID'], ),
    sa.PrimaryKeyConstraint('prescriptionDetailID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescriptiondetails')
    op.drop_table('prescriptions')
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_patientID'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_doctorID'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_diagnosisDate'))

    op.drop_table('diagnosis')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_patientID'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctorID'))
        batch_op.drop_index(batch_op.f('ix_appointments_centerID'))
        batch_op.drop_index(batch_op.f('ix_appointments_appointmentDateTime'))

    op.drop_table('appointments')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_userID'))
        batch_op.drop_index(batch_op.f('ix_patients_omangnumber'))

    op.drop_table('patients')
    op.drop_table('auditlogs')
    op.drop_table('users')
    op.drop_table('centers')
    # ### end Alembic commands ###
