"""empty message

Revision ID: 94f9e84e9de9
Revises: 3c27419ae40b
Create Date: 2026-02-15 14:12:03.957525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f9e84e9de9'
down_revision = '3c27419ae40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointmentID', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_diagnosis_appointmentID'), ['appointmentID'], unique=False)
        batch_op.create_foreign_key(None, 'appointments', ['appointmentID'], ['appointmentID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_diagnosis_appointmentID'))
        batch_op.drop_column('appointmentID')

    # ### end Alembic commands ###
